import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useClerk, useUser } from "@clerk/clerk-react";
import { DarkModeToggle } from "../darkMode/darkModeToggle";
import { Link, NavLink } from "react-router-dom";
const Header = () => {
    const { isSignedIn } = useUser();
    const { signOut } = useClerk();
    return (_jsxs("nav", { className: "flex md:min-w-[1350px] place-items-center justify-between mx-auto px-[5px] md:px-[40px] h-[83px] border-slate-200 border-b-[1px]", children: [_jsx("a", { href: "/", children: _jsx("div", { className: " bg-[url('./assets/images/Frame121.png')] w-[49px] h-[54px]" }) }), _jsx("div", { className: "hidden md:flex", children: !isSignedIn ? (_jsx("ul", { children: isSignedIn !== undefined && (_jsx("li", { className: "font-inter text-[16px] hover:scale-110 transition-transform duration-200 easy-in-out", children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive
                                ? "text-emerald-900 hover:text-emeral-400"
                                : "text-slate-500 hover:text-slate-900", children: "Home" }) })) })) : (_jsxs("ul", { className: "flex relative md:gap-[16px] gap-[10px] md:p-[16px]", children: [isSignedIn !== undefined && (_jsx("li", { className: "font-inter text-[16px] hover:scale-110 transition-transform duration-200 easy-in-out", children: _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive
                                    ? "text-emerald-900 hover:text-emeral-400"
                                    : "text-slate-500 hover:text-slate-900", children: "Home" }) })), _jsx("li", { className: "font-inter text-[16px] hover:scale-110 transition-transform duration-200 easy-in-out", children: _jsx(NavLink, { to: "/products", className: ({ isActive }) => isActive
                                    ? "text-emerald-900 hover:text-emeral-700"
                                    : "text-slate-500 hover:text-slate-600", children: "Poducts" }) }), _jsx("li", { className: "font-inter text-[16px] hover:scale-110 transition-transform duration-200 easy-in-out", children: _jsx(NavLink, { to: "/user-config", className: ({ isActive }) => isActive
                                    ? "text-emerald-900 hover:text-emeral-700"
                                    : "text-slate-500 hover:text-slate-600", children: "About me" }) })] })) }), _jsx("div", { children: isSignedIn ? (_jsx(_Fragment, { children: _jsxs("div", { className: "flex gap-4", children: [isSignedIn !== undefined && _jsx(DarkModeToggle, {}), _jsx(Link, { to: "/", className: "md:min-h-[48px] md:px-[40px] md:py-[12px] py-2 px-2 cursor-pointer bg-emerald-900 hover:bg-emerald-700 rounded-[8px] text-white", children: _jsx("button", { onClick: () => signOut(), className: "cursor-pointer text-white", children: isSignedIn === undefined ? (_jsx("div", { className: "w-5 h-5 border-4 border-gray-300 border-t-primary rounded-full animate-spin" })) : ("Log out") }) })] }) })) : (_jsxs("ul", { className: "font-[inter] text-[16px] flex gap-[40px]", children: [isSignedIn !== undefined && (_jsxs(_Fragment, { children: [_jsx("li", { children: _jsx(DarkModeToggle, {}) }), _jsx("li", { children: _jsx(Link, { to: "register", children: _jsx("button", { className: "my-[12px] cursor-pointer", children: "Register" }) }) })] })), _jsx("li", { children: _jsx(Link, { to: "/login", children: _jsx("button", { className: " md:min-w-[135px] md:min-h-[48px] md:px-[40px] md:py-[12px] py-2 px-2 bg-emerald-900 hover:bg-emerald-700 cursor-pointer rounded-[8px] text-white", children: isSignedIn === undefined ? (_jsx("div", { className: "w-5 h-5 border-4 border-gray-300 border-t-primary rounded-full animate-spin mx-auto" })) : ("Log in") }) }) })] })) })] }));
};
export default Header;
